# Generated by Django 4.2.7 on 2023-11-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_livro_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='dt_ataulizacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='dt_cadastramento',
            field=models.DateField(auto_now_add=True),
        ),
    ]
