# Generated by Django 4.2.7 on 2023-11-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_leitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitor',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
