# Generated by Django 4.2.7 on 2023-11-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
